- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- copyToInstance.sh.example
1. edit `copyToInstance.sh.example` and set 'path' to the path to your dev instance.
2. rename the script to remove `.example`
3. run the script with 
```bash
bash copyToInstance.sh
```
to copy all files from /overrides to your instance folder.
this allows you to modify the files in the git repo and then push them to your instance which allows for git tracking while you work!
if using vscode, install the recommended extension [run it on](https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on) to automatically apply changes on save. 
if on windows, I recommend installing [gitbash](https://git-scm.com/downloads) if you don't have it yet, as Windows cant natively run bash scripts and trying to write a .bat file was giving me a headache
> add bash script to copy contents of overrides folder to mc instance

- overrides/scripts/recipes/misc/smelt_raw_blocks.zs
**Blocks added:** 
copper_block
gold_block
iron_block
qaquite_block
charoite_block
falsite_block
horizonite_block
ventium_block
zinc_block
bismuth_block
irradium_block
silver_block
> added recipes for blasting raw ore blocks

- overrides/scripts/createstages.zs
> gated elixir satchel to witch eye

- overrides/config/ftbquests/quests/chapters/all_things_food.snbt
Added the food items to the "it's not f****ing raw!" quest
Related to issue #172 
Issue not closed, don't need to be yet
> added cooked food for it's not fucking raw quest

- overrides/config/biggerstacks-rules.xml
Made a condition to big stack rule so that the skillets cannot be duplicated. Skillet are now unstackable
Issue was #166 
Issue can be closed after review
> Skillet Duplication Fix/Stackability

- overrides/scripts/mod-interaction-bugs/pickarang_waystones.zs
> add waystone variants and .withoutTag() to rangs

- overrides/config/ftbquests/quests/chapters/temps.snbt
- overrides/scripts/itemstats/armor_progression/adamantite_armor.zs
quest book opens on welcome now
Someone should actually test this since idk if it works on other peoples end
> quest book opens on welcome now

- overrides/config/ftbquests/quests/chapters/easy_eyes.snbt
- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
- overrides/config/ftbquests/quests/chapters/optional_checklists.snbt
- overrides/scripts/tag_manager.zs
or filter to account for magical eye tags 
and fixed text for finding infernal pumpklin
> added OR filter for quests and changed some text

- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
- overrides/config/ftbquests/quests/chapters/shop.snbt
- overrides/config/ftbquests/quests/chapters/temps.snbt
- overrides/config/ftbquests/quests/chapters/the_final_chapter.snbt
- overrides/config/ftbquests/quests/chapters/useful_items.snbt
- overrides/config/ftbquests/quests/data.snbt
- overrides/scripts/tag_manager.zs
Updated Cursed eye, removed some toasts, and fixed debug QB reset
> finished cursed eye

- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
They got overwritten at some point, I brough the changes back
> fixed cold and witch eye

- overrides/scripts/recipes/create/blaze_burner.zs
Added blaze burner recipe back!
> adding blazer burner crafting back

- .vscode/extensions.json
- README.md
big long readme with all the instructions I could think of that a new dev might need!
please let me know if anything doesn't make sense in it
> update readme and add zslint to recommended extensions

- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
Fixed medium eyes being gone in the QB and consolidated totem rewards
> Fixed medium eyes not showing up

- overrides/config/ftbquests/quests/chapters/hard_eyes.snbt
> updated nether eye

- overrides/config/ftbquests/quests/chapters/hard_eyes.snbt
- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
Done
Too many quests to be bother to add photos (sorry) its been hours though
Closes #50
> finished wither eye

- overrides/config/ftbquests/quests/chapters/hard_eyes.snbt
Updated Cryptic eye! One more to go (:
> updated cryptic eye

- overrides/config/ftbquests/quests/chapters/53659F546FCEEC84.snbt
- overrides/config/ftbquests/quests/chapters/temps.snbt
- overrides/scripts/createstages.zs
> Questbook now gives lore!

- overrides/config/ftbquests/quests/chapters/quests.snbt
I added 3 fruits and 1 root from Enlightend
> Added 3 fruits and 1 root

- overrides/config/ftbquests/quests/chapters/quests.snbt
Added one of the 9 stove/oven from Bakery mod in the furnace quest
> added new Bakery stove

- overrides/config/incontrol/spawn.json
decreased spawn rates of blastling, watchling, snareling, and end_enderman
closes #217
> Decreased enderman spawns

- overrides/config/pdgamerules-common.toml
change to MobLoot false to true for nether dim
> MobLoot in Nether

- overrides/config/ftbquests/quests/chapters/quests.snbt
Added Strawberry Seeds and Oat seed to QB quest
> Added Strawberry Seeds and Oat seed to QB

- overrides/config/ftbquests/quests/chapters/quests.snbt
Added the cooked cod and cooked salmon that were missing in the cooking quest in questbook
> Added 2 missing fishes in quests

- overrides/config/ftbquests/quests/chapters/shop.snbt
closes #304 
fixed on dev server already
> add back dependancies to quests for trinkets in shop

- overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
Reverts chocolate-edition/Chocolate-Edition#329
> Revert "Fixed bag of horrors"

- overrides/config/ftbquests/quests/chapters/quests.snbt
Updated early stone quest and added 2 new cooked food from born in chaos
> Updated 2 Quests

- overrides/config/ftbquests/quests/chapters/quests.snbt
- overrides/config/nameless_trinkets/missing_page.json
Added new quest "Flowey - Basil's Catalogue"
> New Quest for Flowers 2.0

- overrides/config/ftbquests/quests/chapters/quests.snbt
- overrides/config/nameless_trinkets/spider_legs.json
New Quest for killing most of the arthropods ingame
> New Quest Arthropods

- overrides/config/ftbquests/quests/chapters/quests.snbt
Added missing Strawberry and Marigolds
> Added missing Flower and Fruit

- overrides/config/ftbquests/quests/chapters/quests.snbt
- overrides/scripts/createstages.zs
- overrides/scripts/upgrading/iron_to_diamond.zs
develop is now for everything going in the next update!
> merge Post 1.5.4 develop

- overrides/config/ftbquests/quests/chapters/quests.snbt
Added 3 missing items and removed duplicate reward
> Added Missing Quest Items

- overrides/config/incontrol/spawn.json
These mobs will go to blue skies in the future
Salmon and Cod don't spawn anymore in blue skies too
> Denier of spawn for 2 mobs

- overrides/config/Spelunkers Charm.toml
- overrides/config/alexsmobs/skreecher.json
- overrides/config/incontrol/spawn.json
Added Tremor config file, removed seal from caves, made skreecher spawn more
> Added Tremor config file, removed seal from caves, made skreecher

- overrides/config/cataclysm.toml
- overrides/config/ftbquests/quests/chapters/quests.snbt
Amethyst Crab have more chance to spawn in lush caves Fix Passion Fruit broken id in quest with new version of atmospheric
> More Amethysr Crabs in lush/fix passionfruit broken in quest

- overrides/config/ftbquests/quests/chapters/quests.snbt
- overrides/config/incontrol/spawn.json
Quest updated for new Atmospheric, Environmental
and Endergetic update.
Testing a click event if you click on the creeper on the quest No lumby in caves
> Added Quests for mods

- overrides/scripts/createstages.zs
changed it to "You need X eyes to use this item"
> Changed unfamiliar item name

- overrides/scripts/createstages.zs
> allow crafting gated items using the crafting terminal

- overrides/scripts/tag_manager.zs
> added meatball to meats tag

- overrides/config/incontrol/loot.json
> removed tempest pearl from scallop loot pool

- overrides/config/blockswap/block_swap.json5
> swapped blocks

- overrides/config/incontrol/spawn.json
> disable laggy penguin spawns and limit dragonfly to 25

- overrides/scripts/recipes/minecraft/pigstep.zs
- overrides/scripts/recipes/musictriggers/blank_disc.zs
- overrides/scripts/removed-recipes/music_triggers.zs
> added pigstep recipe

- overrides/config/biggerstacks-rules.xml
> added powdered snow to blacklist

- overrides/scripts/recipes/alexs_mobs/mosquito_larva.zs
- overrides/scripts/removed-recipes/alexs_mobs.zs
- overrides/scripts/tag_manager.zs
> added corpose maggot to maggot tag

- overrides/config/paxi/datapacks/wdaspacingtweaked.zip
moved down the 3 WDA end ships from 250 to 200. bundled in with one of the other WDA datapacks
closes #612
> WDA end ships down 50

- overrides/scripts/recipes/mutant/chemical_x.zs
didn't touch the tags cause don't think they're breaking anything with this system, they'll need to be removed later. the errors gone like this. works on my end+windows server
> linux moment? idk

- overrides/scripts/recipes/mutant/chemical_x.zs
- overrides/scripts/tag_manager.zs
add chem x recipes directly without tags
> fix chemical x tags not loading

- src/overrides/config/ftbquests/quests/chapters/53659F546FCEEC84.snbt
- src/overrides/scripts/createstages.zs
> add meat shredder and gatling to stage 5

- src/overrides/config/paxi/resourcepacks/choccompatv1.3/assets/chocolate/lang/en_us.json
> update chemical x jei description

- src/overrides/config/pdgamerules-common.toml
set gamerule nightmare stalker false (spawns in through incontrol)and maggots appearance false
closes #598
> nightmare stalker and maggots gamerules

- src/overrides/config/ftbquests/quests/chapters/optional_tips_and_tricks.snbt
- src/overrides/config/paxi/resourcepacks/choccompatv1.3/assets/chocolate/lang/en_us.json
> add note to chem x that it only works on vanilla variants

- src/overrides/config/shouldersurfing-client.toml
> adjust shoulder surfing defaults

- src/manifest.json
- src/modlist.html
Description:
This PR implements an update to calm mornings, which was causing the instance to crash when waking up from using a bed.
Changes:
Updates calm mornings from 4.0.3 to 4.0.4
Fixes:
#752
> update calm mornings to 4.0.4

- src/overrides/config/xaerominimap.txt
- src/overrides/config/xaerominimap_entities.json
- src/overrides/config/xaeroplus.txt
- src/overrides/config/xaeroworldmap.txt
> disable xaero update notifications

- README.md
slightly modified workflow going forward to support working on multiple update features at once. 
[Patches and bugs](https://github.com/orgs/chocolate-edition/projects/1) issues work the same, branch off develop and whatnot. however now, once a PR is merged, Prs should be opened from develop to each future update branch. this can be done by the reviewer on approval, or by the PR author 
other projects like [1.9 spawning](https://github.com/orgs/chocolate-edition/projects/8) should be used in conjuction with their respective 1.x-develop branch. ex `1.9-develop` 
these major feature branches work the save as develop. when working on an issue from one of these lists, be sure to first checkout to the 1.x-develop branch and pull, then checkout to your feature branch. PRs are still required …
> Update contribution guide

- src/overrides/config/incontrol/spawn.json
- src/overrides/config/incontrol/spawner.json
- src/overrides/config/spawnbalanceutility/BiomeMobWeight.csv
wasn't sure if I was supposed to zero out/delete the line in biomemob weight.
incontrol line added cause i want them DEAD
> the 3 crashing mobs

- src/overrides/config/modernfix-mixins.properties
my minecart never came back... sealed forever...
> modernfix remove spawn chunk worked

- src/overrides/config/incontrol/spawn.json
- src/overrides/config/spawnbalanceutility/BiomeMobWeight.csv
> underminer removal

- server pack creator profile/theChocolateEdition.conf
closes #851 
excludes from server pack: paxi resourcepacks, fancymenu images, music trigger songs etc
> update server pack creator configuration to exclude large client side files

- src/manifest.json
- src/modlist.html
- src/overrides/config/resourcepackoverrides.json
> add toastr's xaero icons RP
