chocolate-edition/Chocolate-Edition

overrides/scripts/mod-interaction-bugs/pickarang_waystones.zs

closes #200 
stops pickarangs from breaking waystones. this stops the ability to steal waystones from villages and also will stop from accidentally breaking a waystone if a player tries to right click it from too far away.

stop pickarangs from breaking waystones

---

overrides/scripts/mod-interaction-bugs/iter_enlightened_stones.zs

closes #15 
forces drops for iter and enlightened end stones (blocks marked with mineable/pickaxe) when mined using a tetra tool or pickarang

drop from appropriate loot table for bugged blocks

---

overrides/defaultconfigs/sophisticatedbackpacks-server.toml

Trying to solve the bug with mob spawning with backpack. I think it might have been a double digit change 0.0(1 not shown) to 0.00 (the hidden one only showed while opening the file with VSCode)

Trying to fix backpack spawning with mobs

---

overrides/scripts/createstages.zs

QB is only given upon first joining the world (more specifically upon visiting the OW, but that happens when you spawn in lol)
It was being given twice, but now its not!

making a crafting table no longer gives QB

---

overrides/config/ftbquests/quests/chapters/quests.snbt

the Wither Scuttler is being removed from the new version of born in chaos so I remove it too from the quests

Remove Wither Scuttler from Arthropod Quest

---

overrides/config/ftbquests/quests/chapters/hard_eyes.snbt
overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
overrides/config/paxi/datapacks/chocmobs.zip
overrides/config/spark/activity.json

datapack that changes the min drop of soul vulture heart to 1 instead of 0. and changes sombrero droprate to 100% instead of 20%. changes looting multiplier from 1% to 20% on sombrero but that didn't work, don't see it causing problems so just left it in.

alex mobs drop fix

---

overrides/scripts/recipes/mutant/chemical_x.zs
overrides/scripts/tag_manager.zs

closes #510 
It tells me the tag is empty on a reload, but it works, and it doesnt show on launch soooo 🤷‍♂️

added mutant recipe

---

overrides/config/ftbquests/quests/chapters/settings.snbt
overrides/config/ftbquests/quests/chapters/temps.snbt

toasts for the particles settings would still appear when joining a world for the first time. this fixes that
related to #637

disable all toasts for particles settings quests

---

src/overrides/config/domestication-innovation.toml

should fix #457 .
also disables total recall that can cause a dupe glitch, and amphibian that breaks horses

disable amphibious, total recall and disc jockey enchantments

---

src/overrides/config/alexsmobs.toml

closes #616 
figured its probably best to disable it altogether as anyone wanting to set up base near a beach will have a bad time regardless what food they use.

disable seagul stealing

---

src/overrides/config/MusicTriggers/Chocolate/main.toml

closes #725 
normal minecraft has like 10 mins between songs. this should be more reasonable so even if you spend a while in the same biome you arent hearing the same tracks on repeat one after the other. a little bit of silence should be nice !

add 3 minute delay between songs in the same pool

---

src/overrides/config/paxi/datapacks/ChocoStructuresRotFix/data/structure_no_rotate/tags/worldgen/template_pool/do_not_rotate.json
src/overrides/config/paxi/datapacks/ChocoStructuresRotFix/pack.mcmeta

it has all the white palace jigsaws too cause didn't really want to test if having the datapack have everything/just shaded citadel overwrote anything. the mod has all the white palace ones in it already so the white palace was always fine on this update.
separate datapack since don't know if it breaks if the mods not present
closes #781

adds shaded citadel to the rotation whitelist

---

src/overrides/config/ftbquests/quests/chapters/aether.snbt
src/overrides/config/ftbquests/quests/chapters/end.snbt
src/overrides/config/ftbquests/quests/chapters/everdawn__everbright.snbt
src/overrides/config/ftbquests/quests/chapters/nether.snbt
src/overrides/config/ftbquests/quests/chapters/nexus.snbt
src/overrides/config/ftbquests/quests/chapters/overworld.snbt
src/overrides/config/ftbquests/quests/chapters/useful_items.snbt

Also removed free waystone from useful items
I didn't change the descriptions of the Everdawn/Everbright split entries, but can do so if needed. I figure they'd both need to be updated to something relating more unique to each dimension now.
Solves #754

Added waystone dimension rewards

---

src/overrides/config/ftbquests/quests/chapters/useful_items.snbt
src/overrides/config/paxi/resourcepacks/choccompatv1.3/assets/artifacts/lang/en_us.json
src/overrides/config/paxi/resourcepacks/choccompatv1.3/assets/chocolate/lang/en_us.json
src/overrides/scripts/item_descriptions.zs

Updated the QB and added a JEI page to reflect the shield functionality of the umbrella being disabled. I would remove the item description upon hover and the page that adds the description saying it can be used as a glider and shield, but I don't believe there is a way with CraftTweaker to do this currently.
closes #580

Updated the descriptions of artifacts umbrella

---

src/overrides/config/ftbquests/quests/chapters/easy_eyes.snbt
src/overrides/scripts/recipes/create/precision_mechanism.zs

This adds an alternative crafting recipe for the precision mechanism, one where a player won't have to do sequenced assembly if they do not want to. It uses mid-level create items, such as the deployer and sturdy sheet, and will still require to interact a little more in depth with the mod. There has also been a note added to the quest description to tell players this.
closes #792

Add precision mechanism to crafting table

---

src/modlist.html
src/overrides/config/ftbquests/quests/chapters/easy_eyes.snbt

This update will change the mentions of evil eye to clockwork eye to match the correct eye name in ftbquests.
closes #753

updates ftbquest mentions of evileye to clockworkeye

---

src/overrides/scripts/inventory-mod/gear_inventory_tags.zs

create questing *should* only be a client side mod so its excluded from the server pack. butttt it has an item that was added to inventory mod tags. 
so we just remove it from the tags so server scripts dont break!

remove create questing blueprint from inventory items tags

---

src/overrides/config/incontrol/spawn.json

closes #870 
perplayer scales the "amount" by how many players are online. "perchunk" scales by how many chunks are laoded. both options would cause increased amount of spawns allowed around every player when more players are online. 
this change shouldnt affect singleplayer but for servers will likely make mob spawns rarer when more players are online, as opposed to execively increased based on player count

remove the per player scaling of mincount in incontrol spawn config

---

src/overrides/config/ftbquests/quests/chapters/53659F546FCEEC84.snbt
src/overrides/config/ftbquests/quests/chapters/easy_eyes.snbt
src/overrides/config/ftbquests/quests/chapters/hard_eyes.snbt
src/overrides/config/ftbquests/quests/chapters/medium_eyes.snbt
src/overrides/config/ftbquests/quests/chapters/optional_checklists.snbt
src/overrides/config/ftbquests/quests/chapters/optional_tips_and_tricks.snbt
src/overrides/config/ftbquests/quests/chapters/quests.snbt
src/overrides/config/ftbquests/quests/chapters/tips_and_tricks.snbt
src/overrides/scripts/recipes/misc/storagedrawers.zs

Fixes various small issues within the Questbook.
Closes #891 Removes glacium from the Master Metalworker quest, as glacium was not obtainable
Closes #866 Fixes mention of 'night mode' for new map mod
Closes #878 Changes Expert Mode information given in a couple of quests, to say that it is activated by defeating the Wither
Closes #854 Adds a note to a couple of Neptune's Bounty quests to specify which luck effects change the chances
Closes #798 Removes mention of three of Incendium's biomes in a few different quests
Closes #773 Fixes the Lost Eye glow shroom quest to mention how to craft glowstone and remove a reference to Glimmering Wealds
Closes #756 Storage drawer conversion upgrade had no crafting recipe; one was added in the misc folder for crafttweaker to match other recipes
In …

Questbook fixes

---

src/overrides/config/quark-common.toml

enchantment begone documentation says it removes from loot pools+villager pools so freedom from the wrath/slayer questions too closes #899, #544

remove worthless and disabled enchants

---

src/overrides/config/ftbquests/quests/chapters/53659F546FCEEC84.snbt
src/overrides/config/ftbquests/quests/chapters/tips_and_tricks.snbt
src/overrides/config/majruszsdifficulty.json

closes #893 
closes #876 
closes #880 
- fix expert mode activating from entering the nether
- allow mutant zombie, skele, creeper and enderman to spawn in normal mode 
- allow corallsus, coral golem, deepling priest and warlock to spawn in normal mode
- fix questbook entries regarding expert mode

fix expert mode trigger and unblock progression related mobs

---

src/manifest.json
src/modlist.html
src/overrides/config/cataclysm.toml
src/overrides/config/everycomp-wood_types.toml
src/overrides/config/ftbquests/quests/chapters/53659F546FCEEC84.snbt
src/overrides/scripts/createstages.zs

closes #743 
closes #914 
removes archeology api which was removed from CF
gated new items (maledictus cursium items and others)
changelog:
- downgrade Lionfish api
- Fixed Gauntlet of maelstorm's void vortex pull the caster
- Nerfed Guantlet of maelstorm's cooldown and duration
- Fixed the position of the Wide player model for blazing grips and sticky gloves
- Blazing grips and sticky gloves now have visible first-person models
- Added New blocks for future plans
- Updated Netherite Monstrosity Changed sandstorm bottle
- Fixed Grab attack multi bug
- Added Perfect guard in bulwark of flame
- Increased N.M's step height
- Increased N.M's Head bonus Damage (1.35->1.8)
- Fixed Soul black Smith (pillar lava)
- Buffed Void Forge and Infernal Forge
- Fixed Ministrosity's loot table
- Increased …

update cataclysm 2.25 -> 2.46

---

src/overrides/config/paxi/datapacks/chocmobs/data/dungeons_mobs/loot_tables/entities/wildfire.json
src/overrides/config/paxi/datapacks/chocmobs/data/friendsandfoes/loot_tables/entities/wildfire.json

does a little bit of #911 those dungeonsmobs mobs probably need a better solution imo.
the drops for the armor/weapons aren't in the data part of the mod and don't really want to add more unstackables to raid mobs. think all the bad rng drop mobs mentioned there but drowned necro are in some raid

wildfire drops

---

src/overrides/config/paxi/datapacks/chocmobs/data/dungeons_mobs/loot_tables/entities/drowned_necromancer.json

its probably too high now but idk this one sucked last I played. 33% and goes up 10% per looting level

drowned necro trident drop% increase
